ALTER TABLE `user_notifications`
  MODIFY `type` ENUM(
    'friend_request_received',
    'friend_request_accepted',
    'friend_request_declined',
    'comment_report_resolved',
    'comment_report_rejected',
    'comment_author_moderated',
    'article_report_received',
    'article_report_resolved',
    'article_report_rejected',
    'article_author_moderated',
    'article_liked',
    'article_favorited',
    'article_commented',
    'comment_replied',
    'author_subscribed',
    'subscription_published',
    'announcement_published',
    'suggestion_updated',
    'article_appeal_received',
    'article_appeal_resolved',
    'feedback_updated',
    'article_publish_restricted',
    'article_scheduled_publish',
    'article_scheduled_publish_failed',
    'article_scheduled_unpublish',
    'system'
  ) NOT NULL;
