CREATE TABLE `site_settings` (
  `id` INTEGER NOT NULL DEFAULT 1,
  `site_name` VARCHAR(80) NOT NULL DEFAULT 'HLOVET',
  `browser_title` VARCHAR(120) NOT NULL DEFAULT 'HLOVET',
  `logo_path` VARCHAR(512) NOT NULL DEFAULT '/favicon.svg',
  `pwa_icon_path` VARCHAR(512) NOT NULL DEFAULT '/icon-192.png',
  `default_background_url` VARCHAR(512) NOT NULL DEFAULT '/images/hlovet-cloud-blue.jpeg',
  `default_theme_id` VARCHAR(64) NOT NULL DEFAULT 'cloud-blue',
  `default_accent` VARCHAR(7) NOT NULL DEFAULT '#1814f0',
  `default_surface` VARCHAR(7) NOT NULL DEFAULT '#dfc8c8',
  `default_foreground` VARCHAR(7) NOT NULL DEFAULT '#2b2530',
  `default_muted` VARCHAR(7) NOT NULL DEFAULT '#665867',
  `default_card_alpha` INTEGER NOT NULL DEFAULT 50,
  `default_glass_blur` INTEGER NOT NULL DEFAULT 18,
  `default_glass_tint` VARCHAR(7) NOT NULL DEFAULT '#fff3f6',
  `default_glass_tint_alpha` INTEGER NOT NULL DEFAULT 0,
  `registration_open` BOOLEAN NOT NULL DEFAULT true,
  `default_role_code` VARCHAR(64) NOT NULL DEFAULT 'qi_refining',
  `install_page_enabled` BOOLEAN NOT NULL DEFAULT true,
  `apk_history_enabled` BOOLEAN NOT NULL DEFAULT true,
  `apk_auto_cleanup_enabled` BOOLEAN NOT NULL DEFAULT false,
  `apk_retention_count` INTEGER NOT NULL DEFAULT 3,
  `default_article_visibility` ENUM('public', 'authenticated', 'role_restricted', 'private') NOT NULL DEFAULT 'public',
  `article_image_max_size_mb` INTEGER NOT NULL DEFAULT 10,
  `comments_enabled` BOOLEAN NOT NULL DEFAULT true,
  `reports_enabled` BOOLEAN NOT NULL DEFAULT true,
  `notify_article_liked` BOOLEAN NOT NULL DEFAULT true,
  `notify_article_favorited` BOOLEAN NOT NULL DEFAULT true,
  `notify_article_commented` BOOLEAN NOT NULL DEFAULT true,
  `notify_comment_replied` BOOLEAN NOT NULL DEFAULT true,
  `notify_author_subscribed` BOOLEAN NOT NULL DEFAULT true,
  `notify_subscription_published` BOOLEAN NOT NULL DEFAULT true,
  `notify_friend_request` BOOLEAN NOT NULL DEFAULT true,
  `notify_comment_report` BOOLEAN NOT NULL DEFAULT true,
  `notify_system` BOOLEAN NOT NULL DEFAULT true,
  `template_article_liked` VARCHAR(240) NOT NULL DEFAULT '{actor} 点赞了《{article}》。',
  `template_article_favorited` VARCHAR(240) NOT NULL DEFAULT '{actor} 收藏了《{article}》。',
  `template_article_commented` VARCHAR(240) NOT NULL DEFAULT '{actor} 评论了《{article}》。',
  `template_comment_replied` VARCHAR(240) NOT NULL DEFAULT '{actor} 回复了你在《{article}》中的评论。',
  `template_author_subscribed` VARCHAR(240) NOT NULL DEFAULT '{actor} 订阅了你。',
  `template_subscription_published` VARCHAR(240) NOT NULL DEFAULT '{author} 发布了《{article}》。',
  `template_friend_request` VARCHAR(240) NOT NULL DEFAULT '{actor} 向你发送了好友申请。',
  `template_comment_report_handled` VARCHAR(240) NOT NULL DEFAULT '你对《{article}》中评论的举报已{result}。',
  `template_comment_author_moderated` VARCHAR(240) NOT NULL DEFAULT '你在《{article}》中的评论已被{result}。',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,

  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `article_taxonomies` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `kind` ENUM('category', 'tag') NOT NULL,
  `name` VARCHAR(80) NOT NULL,
  `color` VARCHAR(7) NOT NULL DEFAULT '#7c8faa',
  `sort_order` INTEGER NOT NULL DEFAULT 0,
  `enabled` BOOLEAN NOT NULL DEFAULT true,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,

  UNIQUE INDEX `article_taxonomies_kind_name_key`(`kind`, `name`),
  INDEX `article_taxonomies_kind_enabled_sort_order_idx`(`kind`, `enabled`, `sort_order`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT INTO `site_settings` (`id`, `updated_at`)
VALUES (1, CURRENT_TIMESTAMP(3));

INSERT INTO `article_taxonomies` (`kind`, `name`, `color`, `sort_order`, `updated_at`)
VALUES
  ('category', '随笔', '#e98aa9', 10, CURRENT_TIMESTAMP(3)),
  ('category', '技术', '#5b8def', 20, CURRENT_TIMESTAMP(3)),
  ('category', '服务器', '#5f9f8a', 30, CURRENT_TIMESTAMP(3)),
  ('category', '工具', '#8b7be8', 40, CURRENT_TIMESTAMP(3)),
  ('category', '资源', '#d6a33d', 50, CURRENT_TIMESTAMP(3)),
  ('category', '教程', '#43a5bd', 60, CURRENT_TIMESTAMP(3)),
  ('category', '生活', '#e27d60', 70, CURRENT_TIMESTAMP(3)),
  ('category', '公告', '#7c8faa', 80, CURRENT_TIMESTAMP(3)),
  ('tag', 'AI', '#6d5bd0', 10, CURRENT_TIMESTAMP(3)),
  ('tag', '开发', '#5b8def', 20, CURRENT_TIMESTAMP(3)),
  ('tag', '前端', '#43a5bd', 30, CURRENT_TIMESTAMP(3)),
  ('tag', '后端', '#5f9f8a', 40, CURRENT_TIMESTAMP(3)),
  ('tag', '数据库', '#8b7be8', 50, CURRENT_TIMESTAMP(3)),
  ('tag', '运维', '#d6a33d', 60, CURRENT_TIMESTAMP(3)),
  ('tag', '服务器', '#5f9f8a', 70, CURRENT_TIMESTAMP(3)),
  ('tag', '网络', '#4f98ca', 80, CURRENT_TIMESTAMP(3)),
  ('tag', '工具', '#8b7be8', 90, CURRENT_TIMESTAMP(3)),
  ('tag', '资源', '#d6a33d', 100, CURRENT_TIMESTAMP(3)),
  ('tag', '教程', '#43a5bd', 110, CURRENT_TIMESTAMP(3)),
  ('tag', '经验', '#7c8faa', 120, CURRENT_TIMESTAMP(3)),
  ('tag', '随笔', '#e98aa9', 130, CURRENT_TIMESTAMP(3)),
  ('tag', '生活', '#e27d60', 140, CURRENT_TIMESTAMP(3)),
  ('tag', '公告', '#7c8faa', 150, CURRENT_TIMESTAMP(3));
